apiVersion: v1
data:
  logging.level.org.springframework.context: "DEBUG"
  management.endpoints.web.exposure.include: '*'
  server.port: "9001"
  spring.application.name: "platform-config-server"
  spring.cloud.config.server.jdbc.order: "1"
  spring.cloud.config.server.jdbc.sql: "SELECT PROP_KEY, VALUE from properties where APPLICATION=? and PROFILE=? and LABEL=?"
  spring.cloud.config.server.prefix: "/configs"
  spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
  spring.datasource.hikari.connection-timeout: "5000"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.password: "dev"
  spring.datasource.url: "jdbc:mysql://192.168.1.175:3306/config-db?autoReconnect=true&useSSL=false"
  spring.datasource.username: "dev"
  spring.jpa.show-sql: "true"
  spring.profiles.active: "jdbc"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"logging.level.org.springframework.context":"DEBUG","management.endpoints.web.exposure.include":"*","server.port":"9001","spring.application.name":"platform-config-server","spring.cloud.config.server.jdbc.order":"1","spring.cloud.config.server.jdbc.sql":"SELECT PROP_KEY, VALUE from properties where APPLICATION=? and PROFILE=? and LABEL=?","spring.cloud.config.server.prefix":"/configs","spring.datasource.driver-class-name":"com.mysql.jdbc.Driver","spring.datasource.hikari.connection-timeout":"5000","spring.datasource.hikari.maximum-pool-size":"10","spring.datasource.password":"dev","spring.datasource.url":"jdbc:mysql://192.168.0.175:3306/config-db?autoReconnect=true\u0026useSSL=false","spring.datasource.username":"dev","spring.jpa.show-sql":"true","spring.profiles.active":"jdbc"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"platform-config-server-cm","namespace":"platform"}}
  creationTimestamp: "2025-11-03T17:59:17Z"
  name: platform-config-server-cm
  namespace: platform
  resourceVersion: "17666"
  uid: e29e2662-227f-42e5-a91d-cf486d41eeae
